# !! If changes made in this file to credentials before creating the DB remember to make same changes in application.properties file to avoid breaking the DB connection !!

services:
  db:
    image: postgres:15-alpine
    container_name: hosthelper-db
    environment:
      POSTGRES_USER: hosthelper
      POSTGRES_PASSWORD: hosthelperpass
      POSTGRES_DB: hosthelper_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: