services:
  db:
    image: postgres:15-alpine
    container_name: hosthelper-db
    environment:
      POSTGRES_USER: hosthelper
      POSTGRES_PASSWORD: hosthelperpass
      POSTGRES_DB: hosthelper_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: